# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamerHub_app', '0002_gamelist_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelist',
            name='picture_path',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
