# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GamerHub_app', '0004_auto_20171102_0357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='availability',
            new_name='ava1',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='platform',
            new_name='ava2',
        ),
        migrations.AddField(
            model_name='profile',
            name='ava3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='platform1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='platform2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='platform3',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
